# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker  adder_api.api:app --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000